### PR TITLE
Use tomllib/tomli for reading .toml configs

### LINKED ISSUE #599: Also allow other toml file readers
Currently when the library `toml` is missing pydocstyle cannot read the `pyproject.toml` file.

It would be nice if also other toml reader would be supported ([`tomli`](https://pypi.org/project/tomli/)), resp. with python 3.11 the built in [`tomllib`](https://docs.python.org/3.11/library/tomllib.html) library (which is based on `tomli` as far as I know).

### LINKED ISSUE #600: Pydocstyle crashes on literal strings in pyproject.toml
## Problem

When an unrelated configuration (ex `semantic_release`) has a literal string, such as a regular expression, in the configuration denoted by `"""`, pydocstyle will throw a `toml.decoder.TomlDecodeError` for an unterminated string.  This likely does not happen with every literal string but causes errors when there is a single quote inside the regexp.  

My offending config:

```toml
# pyproject.toml

[tool.semantic_release]
version_pattern = [
    # regular expression to find version value in `_version.py` file
    '''src/pkg1/_version.py:__version__[ ]*[:=][ ]*["'](\d+\.\d+\.\d+)["']'''
]

[tool.pydocstyle]
convention = 'pep257'
```

### Log

```log
(venv) $ pydocstyle scripts/prepare.py

Traceback (most recent call last):
  File "/workspaces/py-rpm/venv/bin/pydocstyle", line 8, in <module>
    sys.exit(main())
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/cli.py", line 75, in main
    sys.exit(run_pydocstyle())
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/cli.py", line 41, in run_pydocstyle
    for (
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 288, in get_files_to_check
    config = self._get_config(os.path.abspath(name))
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 369, in _get_config
    config = self._get_config_by_discovery(node)
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 318, in _get_config_by_discovery
    config = self._get_config(parent_dir)
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 369, in _get_config
    config = self._get_config_by_discovery(node)
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 312, in _get_config_by_discovery
    config_file = self._get_config_file_in_folder(path)
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 555, in _get_config_file_in_folder
    if config.read(full_path) and cls._get_section_name(config):
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/pydocstyle/config.py", line 70, in read
    self._config.update(toml.load(fp))
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/workspaces/py-rpm/venv/lib/python3.8/site-packages/toml/decoder.py", line 362, in loads
    raise TomlDecodeError("Unterminated string found."
toml.decoder.TomlDecodeError: Unterminated string found. Reached end of file. (line 121 column 1 char 2619)
```

### Investigation

This seems to be a limitation of the parser implementation and associated TOML standard.  I looked at the dependency trees of `semantic_release` and found that they use the library `tomlkit` instead of `toml` because it supports `v1.0.0` of the TOML standard instead of `v0.5.0`.  Under the hood, it seems there is a few flaws with the parser in `toml==0.5.0` since I can change the regular expression in different variations and get different but not obvious/expected results.  One such oddity, inside a the triple single quotes `'''` if you have two double quotes `"` somewhere within it, it will cause an Unterminated string error, but if only one exists it is fine.  The other variation that shouldn't work but does, is escaping the double quotes (ie. `\"`) and it is fine.

I also found that the `toml` library itself is stale and has not received any updates since Oct 2020.  Whereas [`tomlkit`](https://pypi.org/project/tomlkit/) and its competitor [`tomli`](https://pypi.org/project/tomli/) have both received updates in the 1st half of 2022.  Furthermore, `python3.11` also highlights these two frontrunners as the ideal libraries to read/write toml in the [Python docs](https://docs.python.org/3.11/library/tomllib.html).  Maybe in a year future you can use the `python3.11` built-in library `tomllib` but clearly that would be incompatible for a few years.

Additional discussion on TOML support for raw/literal strings: https://github.com/toml-lang/toml/issues/80

## Recommendation

Switch `toml` dependency to `tomlkit` or `tomli`.  

I have tested both of the variations `tomli==2.0.1` and `tomlkit==0.10.2` and both parse my `pyproject.toml` configuration file (as provided above) with regex correctly without error.  `tomlkit` does seem to be leading in popularity but the `tomli` documentation is a bit better.  Also of note, `tomli.load()` requires the file to have been opened for reading in bytes instead of a specified encoding.

Related: #599

### PR DESCRIPTION
**Pull request by mgorny**
Use the built-in `tomllib` module in Python 3.11 and the modern `tomli` package in older Python versions to read .toml configs instead of the unmaintained and broken `toml` package.

Fixes #599
Fixes #600

---
Thanks for submitting a PR!

Please make sure to check for the following items:
- [x] Add unit tests and integration tests where applicable.  (n/a)
      If you've added an error code or changed an error code behavior,
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [x] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Comment by mgorny** [comment]
Rebased on top of poetry.

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I think this depend on #612 to be really tested, could you rebase on it ?

**Review by samj1912 — APPROVED** [review]

**Comment by samj1912** [comment]
Thanks for this PR!

**Comment by mgorny** [comment]
Thanks!

**Comment by christianbundy** [comment]
This was a breaking change for our team, btw -- we're on Python 3.10 and have had `toml` installed, but updating to the latest version meant that our configuration file was ignored and so we got a bunch of unexpected errors:

```
WARNING: The pyproject.toml configuration file was ignored, because the `tomli` package is not installed.
```

Now that I understand what changed, it's a simple fix, but wanted to let y'all know that this wasn't 100% backward-compatible. Either way, thanks for the improvement -- I'm increasingly excited to join the Python 3.11 gang.

**Comment by samj1912** [comment]
@christianbundy how were you installing pydocstyle with toml support? Were you using `pydocstyle[toml]` ? If so, it should not have been a breaking change.

**Comment by christianbundy** [comment]
We're using pre-commit, here's the config we were using:

```yaml
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.3 # previously using 6.1.1, upgrading caused errors
    hooks:
      - id: pydocstyle
        args:
          - --config=pyproject.toml
        additional_dependencies:
          - toml~=0.10.2
```

Should we have been doing this differently? I think _maybe_ we could add `pydocstyle[toml]` as an additional dependency, but I think that would install pydocstyle twice? Not sure how that would work.

**Comment by samj1912** [comment]
@christianbundy you want the following - 

https://github.com/pre-commit/pre-commit/issues/1526#issuecomment-649938146

**Comment by christianbundy** [comment]
Oh, nice! Thank you.

**Comment by mgorny** [comment]
> @christianbundy you want the following -
> 
> [pre-commit/pre-commit#1526 (comment)](https://github.com/pre-commit/pre-commit/issues/1526#issuecomment-649938146)

Could someone ask upstream to include that in the official documentation? It's not the most predictable way of sorting this particular problem. Unfortunately, I can't do that since upstream likes banning people for no apparent reason.

**Comment by scottstanie** [comment]
Just to spell it out for any others, it took me a few tries to connect the comment above to what we need here. My .pre-commit.yaml now has

```yaml
  - repo: https://github.com/PyCQA/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        additional_dependencies: ['.[toml]']
        exclude: test
```

and it made the `tomli` error go away

**Pull request merged**
