### PR TITLE
Declare Python 3.6 support

### PR DESCRIPTION
**Pull request by jonafato**
- Enabled tests in ``tox.ini`` and ``.travis.yml``
- Declare support for 3.6 in ``README.rst`` and ``docs/release_notes.rst``

Thanks for submitting a PR!

Please make sure to check for the following items:
- [ ] Add unit tests and integration tests where applicable.  
      If you've added a error code or changed an error code behavior, 
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [x] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Comment by jonafato** [comment]
This error when building the docs is unrelated to my change and appears to be isolated to sphinx==1.6.3. When testing locally using 1.6.2 or sphinx master, the docs build without issue. Once the next version of sphinx is released, the failure should go away on its own.

**Comment by Nurdok** [comment]
In that case, can you pin down the Sphinx version in the docs requirements file? That way, the build will pass and I could merge this.

**Comment by jonafato** [comment]
@Nurdok sphinx pinned, travis passing.

**Comment by Nurdok** [comment]
@jonafato Merged! Thanks for taking the time to do this and to investigate the Sphinx failure.

**Pull request merged**
