### PR TITLE
Add Python 3.11 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
Thanks for submitting a PR!

Please make sure to check for the following items:
- [x] Add unit tests and integration tests where applicable.  
      If you've added an error code or changed an error code behavior,
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [ ] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Comment by cclauss** [comment]
Should help to test  #608

**Comment by cclauss** [comment]
On Python 3.11...
```
Running Sphinx v1.6.2
making output directory...

Exception occurred:
  File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 3
```

**Comment by cclauss** [comment]
@serhiy-storchaka Your thoughts, please?

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Isn't this co-dependant with #608 ? One of you should probably cherry-pick the change from the other one right ?

**Comment by serhiy-storchaka** [comment]
Is the full traceback available? This can help identify the regular expression that needs to be corrected.

**Comment by samj1912** [comment]
The failure was happening in Sphinx. Since we have enabled read the docs PR apps, the doc generation in github actions is no longer needed. A larger term fix would involve updating the Sphinx version (from 1.6.x to 6.0)

**Review by samj1912 — APPROVED** [review]

**Pull request merged**
