### PR TITLE
Invalid escape sequence fixes

### PR DESCRIPTION
**Pull request by scop**
Thanks for submitting a PR!

Please make sure to check for the following items:
- [ ] Add unit tests and integration tests where applicable.  
      If you've added an error code or changed an error code behavior,
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [x] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Comment by scop** [comment]
Done, hope I got it right now. Let me know if you'd prefer a clean rebase instead of what's here now.

**Comment by Nurdok** [comment]
Looks correct, but what issue does this fix exactly? Can you add some tests?

**Comment by scop** [comment]
Avoids warnings:
```
$ python3 -Wd -c 'foo = "[^\.].*"'
<string>:1: DeprecationWarning: invalid escape sequence \.
```
...which will become errors at some point, https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals
> Changed in version 3.6: Unrecognized escape sequences produce a DeprecationWarning. In some future version of Python they will be a SyntaxError.

Wrt testing, I think it's indirect and kind of out of scope for this PR, but running tests with warnings enabled and someone looking at the logs would do somewhat. Or maybe turn them to errors. Probably requires upgrading pytest to >= 3.1 and... something, maybe a -Wd flag to pytest (although that didn't catch these for some reason in a quick test).

**Comment by asottile** [comment]
In python3.8 this becomes a SyntaxWarning and in future versions this will be a SyntaxError

**Comment by samj1912** [comment]
Re: tests, now that we have py3.8 in the CI, should we just add a -W flag to pytest so that it fails on any warnings that are emitted? This will ensure that there are no future regex additions like these.

**Review by samj1912 — APPROVED** [review]

**Comment by samj1912** [comment]
Closing this as it has been inactive for a while. Please feel free to re-open if this is still relevant.

**Comment by asottile** [comment]
it looks like #445 superseded this

**Pull request closed without merging**
