### PR TITLE
fix: do not pass file names with pre-commit

### PR DESCRIPTION
**Pull request by yajo**
This is the only way pydocstyle will obey its own match rules.

Thanks for submitting a PR!

Please make sure to check for the following items:
- [x] Add unit tests and integration tests where applicable.  
      If you've added an error code or changed an error code behavior,
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [x] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Review by samj1912 — APPROVED** [review]

**Comment by bszonye** [comment]
This change is causing pre-commit to emit a warning:
```
$ pre-commit run --all-files
[WARNING] Unexpected key(s) present on https://github.com/pycqa/pydocstyle => pydocstyle: pass_file_names
```

**Comment by bszonye** [comment]
Also, this appears to change the documented behavior here:
https://www.pydocstyle.org/en/stable/usage.html?highlight=pre-commit#usage-with-the-pre-commit-git-hooks-framework

> Checked-in python files will be passed as positional arguments so no need to use `--match=*.py`. You can also use command line arguments instead of configuration files to achieve the same effect with less files.

If that's changing then the documentation needs an update and possibly instructions for how to get the old behavior.

**Comment by bszonye** [comment]
Should I move my comments here to a new issue? I noticed that a revert commit has been opened and closed a couple times now.

**Comment by samj1912** [comment]
This commit has been reverted.

**Comment by bszonye** [comment]
Thanks! By the way, I discovered accidentally that the underlying issue that motivated this PR might have already been addressed. Please see my comment here:
https://github.com/PyCQA/pydocstyle/issues/111#issuecomment-1374921227

**Comment by bszonye** [comment]
Aha, I was still seeing the error in pre-commit because this:
```
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.2.3
  hooks:
  - id: pydocstyle
```
gets the broken config from the 6.2.3 release. Reverting my config to 6.2.2 works around the problem.

**Pull request merged**
