### PR TITLE
Convert module to package

### PR DESCRIPTION
**Pull request by lordmauve**
This enables the addition of package data such as wordlists.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
If we're turning this into a package, I'd really rather not have everything shoved into `__init__.py`.

**Comment by lordmauve** [comment]
Yes, but I thought it would be harder to review a split into submodules at the same time as a pivot from module to package.

**Comment by sigmavirus24** [comment]
Sure. I'm just hoping this doesn't persist too long after this is merged.

**Comment by jayvdb** [comment]
Create a new task and suggest a split layout ?

**Comment by Nurdok** [comment]
Hey guys, I saw a bunch of PRs were opened. I just wanted to let you know it'll take me a week or two to get around to review them. Don't despair, and thanks for the effort!

**Comment by Nurdok** [comment]
Closing as this is no longer relevant.

**Pull request closed without merging**
