### PR TITLE
Upgrade Python syntax with pyupgrade --py3-plus

### PR DESCRIPTION
**Pull request by hugovk**
Upgraded Python syntax with [`pyupgrade --py3-plus`](https://github.com/asottile/pyupgrade).

---

Thanks for submitting a PR!

Please make sure to check for the following items:
- [x] Add unit tests and integration tests where applicable.  
      If you've added an error code or changed an error code behavior,
      you should probably add or change a test case file under `tests/test_cases/` and add 
      it to the list under `tests/test_definitions.py`.  
      If you've added or changed a command line option,
      you should probably add or change a test in `tests/test_integration.py`.
- [ ] Add a line to the release notes (docs/release_notes.rst) under "Current Development Version".  
      Make sure to include the PR number after you open and get one.
   
Please don't get discouraged as it may take a while to get a review.

### CODE REVIEW

**Comment by hugovk** [comment]
I hadn't seen #341. If it overlaps, feel free to close this and re-run the tool on that branch!

**Comment by Nurdok** [comment]
Hi @hugovk, thanks for doing this! I don't want to steal your thunder, do you want to wait for #341 to be merged and then rerun on this branch? I'll let you know when I merge it.

Happy Hacktoberfest!

**Comment by hugovk** [comment]
Oh, It's not much thunder, it's just running a tool :) Either way is fine!

**Comment by hugovk** [comment]
Rebased on master (no merge conflicts!) and re-ran the tool (no new changes!).

**Comment by Nurdok** [comment]
Merged. Thanks for doing this!

**Pull request merged**
